apiVersion: v1
kind: Service
metadata:
    name: my-service
    namespace: devops
    labels:
      app: jenkins-server
    # Set Loadbalancer as external
    annotations:
        cloud.google.com/load-balancer-type: "External"
spec:
  type: LoadBalancer
  selector:
    app: jenkins-server
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000