apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-server
  template:
    metadata:
      labels:
        app: jenkins-server
    spec:
      # For Jenkins pod to be able to write to the local persistent volume
      securityContext:
            fsGroup: 1000 
            runAsUser: 1000
      serviceAccountName: jenkins-admin
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
              claimName: jenkins-pv-claim
      #  
        - name: docker-deamon
          hostPath:
            path: /var/run/docker.sock

      containers:
        - name: jenkins
        # setup my own jenkins_with_docker image
          image: rizk95/jenkins_with_docker_terra_ansible_kubectl:latest
          resources:
            # limits:
            #   memory: "2Gi"
            #   cpu: "1000m"
            # requests:
            #   memory: "500Mi"
            #   cpu: "500m"
          ports:
            - name: httpport
              containerPort: 8080
            # port 50000 gives you access to a remote Java (JIRA) API
            - name: jnlpport
              containerPort: 50000
          livenessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home 

            - name: docker-deamon
              mountPath: /var/run/docker.sock
      